version: "2"

formatters:
  enable:
    - gofmt         # форматирование
    - goimports     # импорты

linters:
  enable:
    - errcheck      # проверка обработки ошибок
    - govet         # подозрительные конструкции
    - staticcheck   # статический анализ (включает gosimple)
    - unused        # неиспользуемый код
    - ineffassign   # неэффективные присваивания
    - misspell      # опечатки в комментариях
